### ISSUE TITLE
Pre-trained models unavailable

### ISSUE THREAD

**Issue by felipesanmartin** [baudm/HomographyNet#2]
Hello, I tried to download the models' weights, but there are not available due data quota was reached. This is the error message:

batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/baudm/HomographyNet.git/info/lfs'

Can you upload them to another free server? For instance, Dropbox or Google Drive

Thanks a lot.

**Comment by baudm** [comment]
Hi, I'm currently uploading pre-trained weights of some of my projects here:
https://gitlab.com/baudm/model-zoo

I also suggest looking at my other HomographyNet implementation which achieves an even lower mean average corner error than my original MobileNet-based model: https://github.com/baudm/fc-homographynet/

**Comment by felipesanmartin** [comment]
Thanks a lot!
